---
name: Generate GO code

on:
  push:
    tags:
    - v*.*.*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run dockerized lint
        run: make docker-lint
  update-go-package:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout proto repo
        uses: actions/checkout@v2
        with:
          path: proto

      - name: Checkout go-proto repo
        uses: actions/checkout@v2
        with:
          repository: badhouseplants/envspotting-go-proto
          ref: main
          path: go-proto

      - name: Copy proto defenitions
        working-directory: go-proto
        run: cp -R ../proto/proto .

      - name: Build docker image
        working-directory: go-proto
        run: docker build -t generate-go-code .

      - name: Generate go code
        working-directory: go-proto
        run: make docker-protobuf

      - name: Push to main
        working-directory: go-proto
        run: |
          git config --local user.email "dev.allanger@gmail.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          git push --set-upstream https://allanger:$GO_GITHUB_TOKEN@github.com/badhouseplants/envspotting-go-proto main

      - name: Create tag
        working-directory: go-proto
        run: |
          git tag -a ${GITHUB_REF##*/} -m "${{ github.event.head_commit.message }}"
          git push --set-upstream https://user:$GO_GITHUB_TOKEN@github.com/owner/my-repo push origin ${GITHUB_REF##*/}
