---
name: Generate GO code

on:
  push:
    # tags:
    # - v*.*.*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run dockerized lint
        run: make docker-lint
  update-go-package:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout proto repo
        uses: actions/checkout@v2
        with:
          path: proto

      - name: Checkout go-proto repo
        uses: actions/checkout@v2
        with:
          repository: badhouseplants/envspotting-go-proto
          ref: main
          path: go-proto

      - name: Copy proto defenitions
        working-directory: go-proto
        run: cp -R ../proto/proto .

      - name: Build docker image
        working-directory: go-proto
        run: docker build -t generate-go-code .

      - name: Generate go code
        working-directory: go-proto
        run: make docker-protobuf

      - run: echo ${{ github.event.head_commit.message }}
      # - name: Commit files
        # working-directory: go-proto
        # run: |
          # git config --local user.email "dev.allanger[bot]@gmail.com"
          # git config --local user.name "github-actions[bot]"
          # git add .
          # git commit -m ""
