---
name: Generate GO code

on:
  push:
    # tags:
    # - v*.*.*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run dockerized lint
        run: make docker-lint
  update-go-package:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: badhouseplants/envspotting-go-proto
          ref: main
          path: go-proto

      - name: Copy proto defenitions
        run: cp -R ../proto .

      - name: Build docker image
        run: docker build -t generate-go-code .

      - name: Generate go code
        run: make docker-protobuf

      - name: check
        run: ls models
