---
name: Lint

on:
  pull_request:
    paths:
      - "proto/**"
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run dockerized lint 
        run: make docker-lint